### ISSUE TITLE
How to set up the log file and further usb sticks

### ISSUE THREAD

**Issue by renekcl** [markussiebert/homeassistant-addon-vzlogger#3]
Hallo Marcus,

ich habe dein AddOn in HA installiert. Soweit startet der Logger auch. Wie gebe ich das Logfile korrekt in der Config an? In welches Filesystem wird der Container am Ende gemountet?

Kannst du mir sagen wie ich weitere USB Sticks wie /dev/usbtty1 einbinde?

**Comment by markussiebert** [comment]
Hi,

zu 1.:
![image](https://user-images.githubusercontent.com/16692560/219955695-02ac3e91-22e0-4ab9-b218-0e9a0779a621.png)
So sieht meine Addon Config aus, so der Blick aus dem VSCode Server

![image](https://user-images.githubusercontent.com/16692560/219955759-3b0ea121-22ee-4a95-b67a-938d4cf54051.png)

2. Weitere Sticks gehen grad noch nicht, müsste ich mir anschauen - habe aktuell nur einen. Bzw. kannst du gerne auch einen MR stellen. Da man die Config eh selbst schreibt, geht es nur um das mounten des devices in den container... Vielleicht wäre es mit einem zusätzlichen Inputfeld in der config schon getan?

**Comment by renekcl** [comment]
Hi Markus, 

Danke für die Antwort. Ich bin noch recht neu in diesem Umfeld unterwegs. Was meinst du mit "MR" stellen? Es dürfte in der Tat nur darum gehen ein zweites Device in den Container zu mounten. Vorher habe ich das über Portainer gemacht. Auf diese Optionen habe ich ja nun keinen Zugriff mehr durch das Add-On.

**Comment by mr-gosh** [comment]
> Was meinst du mit "MR" stellen?

Das steht für "MergeRequest" - und fordert Dich auf etwas am Code anzupassen und wenn es funktioniert deine Änderungen hier als Verbesserung bei zu tragen.

**Comment by markussiebert** [comment]
Genau,

es müsste in dieser Datei sein:

https://github.com/markussiebert/home-assistant-addons/blob/main/vzlogger/config.json

dort wird die Konfigurationsmaske definiert. 

https://developers.home-assistant.io/docs/add-ons/configuration/

Da die doku dazu ... muss man mal ausprobieren, ob es geht devices 2x zu definieren. Bin mir auch nicht sicher, ob alle devices im container per se schon verfügbar sind? Beim starten des Addons hatte ich einen output drin, (listdevices.sh). Das müsste alle verfügbaren devices ausgeben und dann könntest du ggf. vielleicht einfach im Configfile das 2. addon "benutzen"?

**Comment by markussiebert** [comment]
Bei mir sieht es so aus:

```
[16:54:19] INFO: ==============================================================================
/dev/ttyACM0 - dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2141675
/dev/ttyUSB0 - Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_0092C17D
[16:54:19] INFO: ==============================================================================
```

ich nehme an, ich könnte tatsächlich ohne Änderungen auch das 2. Device in der Config benutzen. Einfach einen 2. meter block rein machen und fertig :-)

**Comment by renekcl** [comment]
Hallo Markus,

ich habe mir das noch einmal angesehen. Du liegst wohl richtig. Alle Devices werden angelistet und sind damit vermutlich auch nutzbar. Ich habe noch ein Problem mit dem Log. Wo genau legt er das an? Ich hatte in der vzlogger.conf schon /share/vzlogger/vzlogger.log angegeben aber immer ein Permission denied bekommen. Hinterlege ich einfach nur vzlogger.conf, ohne Pfad, funktioniert es, aber da weiß ich nicht wo das Log geschrieben wird.

**Comment by markussiebert** [comment]
Du solltest das log nach  "log": "/dev/stdout", schreiben ... damit erscheint es dann direkt im Reiter Logs des Addons

**Comment by GrandAmmor** [comment]
> Du solltest das log nach  "log": "/dev/stdout", schreiben ... damit erscheint es dann direkt im Reiter Logs des Addons

Das brachte bei mir die Lösung. Danke für den Hinweis!

Meine alte config läuft nun unter HA mit deinem Addon und MQTT funktioniert super.

Allerdings steht im Log nun, dass das pushen auf HA-IP:5582 nicht funktioniert (could't connect to server) und der localhost nicht erreichbar sei (CURL: Failed to connect to localhost port 80: Connection refused).

Beides funktionierte, als die gleiche config auf einem Zero 2 W lief. Was mache ich falsch? Soll ich ein neues Issue aufmachen?

**Comment by markussiebert** [comment]
Hi sorry für die späte antwort .... hast du das mqtt addon aktiviert?

meine mqtt config sieht so aus:

```json
    "mqtt": {
        "enabled": true,
        "host": "192.168.1.11",
        "port": 1883,
        "id": "vzlogger",
        "cafile": "",
        "capath": "",
        "certfile": "",
        "keyfile": "",
        "keypass": "",
        "keepalive": 30,
        "topic": "vzlogger/data",
        "user": "redacted,
        "pass": "redacted",
        "retain": false,
        "rawAndAgg": false,
        "qos": 0,
        "timestamp": false
    },
```
